version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"

  notification-service:
    build: .
    container_name: notification-service
    depends_on:
      - rabbitmq
      - mongo
    environment:
      - RABBITMQ_URL=amqp://rabbitmq
      - MONGO_URL=mongodb://mongo:27017/notifications
      - GMAIL_USER=clearskyntua@gmail.com
      - GMAIL_PASS=mqtp tarq kply eaxl
    volumes:
      - .:/app
    working_dir: /app
    command: node index.js
