version: '3.8'

services:
  mongo:
    image: mongo
    container_name: microservice01-mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  app:
    build:
      context: .
    container_name: microservice01-app
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/grades
    depends_on:
      - mongo

volumes:
  mongo_data: