services:
  review-service:
    build: .
    ports:
      - "8400:8400"
    environment:
      MONGO_URI: mongodb://mongodb:27017/reviewDB
      PORT: 8400
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - clearsky-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    networks:
      - clearsky-network

volumes:
  mongo-data:

networks:
  clearsky-network:
    driver: bridge
    external: true