# docker-compose.yml
services:
  review-service:
    build: .
    ports:
      - "8400:8400" # Exposes the service on host port 8400 [user requirement]
    environment:
      MONGO_URI: mongodb://mongodb:27017/reviewDB
      PORT: 8400
    depends_on:
      - mongodb
    volumes:
      - .:/app # Optional: For development, mounts current directory to /app in container
      - /app/node_modules # Optional: To use node_modules from container, not host
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017" # Expose MongoDB if you want to connect from host
    volumes:
      - mongo-data:/data/db # Persist MongoDB data
    restart: unless-stopped

volumes:
  mongo-data: