version: '3'

services:
  institution-credit-service:
    build: .
    ports:
      - "8102:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGODB_URI=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:27017/institutionCredits?authSource=admin
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - clearsky-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    networks:
      - clearsky-network

networks:
  clearsky-network:
    driver: bridge

volumes:
  mongodb_data: