services:
  institution-credit-service:
    build: .
    ports:
      - "8102:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGODB_URI=${MONGODB_URI}
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - clearsky-network

  credit-mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    networks:
      - clearsky-network

networks:
  clearsky-network:
    driver: bridge

volumes:
  mongodb_data: