version: '3.8'
services:
  krakend:
    image: devopsfaith/krakend:2.7
    ports:
      - "8080:8080"
      - "8090:8090"  # Metrics endpoint
    volumes:
      - ./krakend.json:/etc/krakend/krakend.json:ro
      - ./krakend-logs:/var/log/krakend
    environment:
      - KRAKEND_PORT=8080
      - FC_ENABLE=1
      - FC_SETTINGS=/etc/krakend/settings
      - FC_PARTIALS=/etc/krakend/partials
      - FC_OUT=/etc/krakend/krakend.json
    depends_on:
      - user-auth-service
      - institution-auth-service
      - user-management-service
      - institution-service
      - institution-credits-service
      - grade-service
      - statistics-service
      - notification-service
      - review-service
      - user-flow-orchestrator
      - grade-lifecycle-orchestrator
      - review-orchestrator
    networks:
      - clearsky-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/__health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s