services:
  review-service:
    build: .
    ports:
      - "8400:8400"
    env_file:
      - .env
    environment:
      - PORT= 8400
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGODB_URI=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:27017/reviewDB?authSource=reviewDB
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - clearsky-network

  review-mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - PORT=8400
      - MONGODB_URI=mongodb://review-mongodb:27017/review?authSource=admin
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    networks:
      - clearsky-network

volumes:
  mongo-data:

networks:
  clearsky-network:
    driver: bridge
    external: true