openapi: 3.0.3
info:
  title: Review Service API
  version: 1.0.0
  description: API for managing reviews.

servers:
  - url: http://localhost:8400/api/reviews
    description: Local development server

paths:
  /:
    post:
      summary: Create a new review
      operationId: createReview
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReviewInput'
      responses:
        '201':
          description: Review created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
        '400':
          description: Invalid input data
    get:
      summary: Get all reviews
      operationId: getAllReviews
      parameters:
        - in: query
          name: filter
          schema:
            type: string
          description: Filter reviews based on query parameters
      responses:
        '200':
          description: List of reviews
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Review'
        '500':
          description: Internal server error

  /{id}:
    get:
      summary: Get a review by ID
      operationId: getReviewById
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Review ID
      responses:
        '200':
          description: Review details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
        '404':
          description: Review not found
        '500':
          description: Internal server error
    put:
      summary: Update a review
      operationId: updateReview
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Review ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReviewUpdate'
      responses:
        '200':
          description: Review updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
        '400':
          description: Invalid input data
        '404':
          description: Review not found
    delete:
      summary: Delete a review
      operationId: deleteReview
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Review ID
      responses:
        '200':
          description: Review deleted successfully
        '404':
          description: Review not found
        '500':
          description: Internal server error

components:
  schemas:
    Review:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the review
        studentId:
          type: string
          description: Student's unique identifier
        courseId:
          type: string
          description: Course's unique identifier
        gradeId:
          type: string
          description: Grade's unique identifier
        studentRegistrationNumber:
          type: string
          description: Student's registration number
        reason:
          type: string
          description: Reason for the review
        status:
          type: string
          description: Status of the review
        instructorResponse:
          type: string
          description: Instructor's response
        reviewedGrade:
          type: string
          description: Reviewed grade
        createdAt:
          type: string
          format: date-time
          description: Creation timestamp
        updatedAt:
          type: string
          format: date-time